<?php
/**
 * Socket class
 *
 * @license GPL
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License, version 3
 * @author  QTIƎE <Qti3eQti3e@Gmail.com>
 */

namespace core\rocket;


use core\ws\server;

/**
 * Class socket
 * Handle socket connections
 * @package core\rocket
 */
class socket extends server{
	protected function process($user, $message) {

	}
	protected function connected($user) {
		// TODO: Implement connected() method.
	}
	protected function closed($user) {
		// TODO: Implement closed() method.
	}
	protected function checkOrigin($origin) {
		return parent::checkOrigin($origin); // TODO: Change the autogenerated stub
	}
	protected function checkIP($ip) {
		return parent::checkIP($ip); // TODO: Change the autogenerated stub
	}
}